#!/usr/bin/perl

BEGIN {
use File::Basename;
use lib dirname $0;
}
$ENV{DNS_ADMIN} = 'admin' unless defined $ENV{DNS_ADMIN};

use sysami::util;
use veridns::zone;
use veridns::zone::db;
die "no zone name specified\n" unless defined $ARGV[0];
my $dbh = vdb_open();
die "no db\n" unless defined $dbh;
z_delete($ARGV[0],$ENV{'DNS_ADMIN'},$dbh);
exit(0);

