#!/usr/bin/perl

BEGIN {
use File::Basename;
use lib dirname $0;

}
$ENV{DNS_ADMIN} = 'admin' unless defined $ENV{DNS_ADMIN};

use sysami::util;
use veridns::zone;
use veridns::zone::db;
die "no zone name specified\n" unless defined $ARGV[0];
die "ERROR\n" unless $ARGV[0] == $ARGV[1];
my $dbh = vdb_open();
die "no db\n" unless defined $dbh;
my $user = get_user(dbh=>$dbh,username=>$ENV{'DNS_ADMIN'});
die "no user" unless defined $user;
z_delete($ARGV[0],$ENV{'DNS_ADMIN'},$dbh);
z_import($ARGV[0],$user,$ARGV[1],$dbh);
exit(0);

