#!/usr/bin/perl

BEGIN {
use File::Basename;
use lib dirname $0;
}
$ENV{DNS_ADMIN} = 'admin' unless defined $ENV{DNS_ADMIN};

use sysami::util;
use veridns::zone;
use veridns::zone::db;
die "no zone name specified\n" unless defined $ARGV[0];
my $zname = $ARGV[0];
my $template = "default";
if (defined $ARGV[1]) {
	$template = $ARGV[1];
} else {
	print "no template specified, will use default template\n" unless defined $ARGV[1];
}

if (-f "$ENV{'TMPDIR'}/$ARGV[0].data") {
	die "zone $ARGV[0] has garbage left in tempdir, or someone is already editing it";
}
my $ifh = undef;
my $ofh = undef;
open($ifh,"<","/sysami/.data/$ENV{'DNS_ADMIN'}/templates/$template.data") or die "can't open template $template\n";
open($ofh,">","$ENV{'TMPDIR'}/$ARGV[0].data") or die "can't open zonefile\n";
while (<$ifh>) {
	s/\$zname/$ARGV[0]/g;
	print $ofh $_;
}
close $ifh;
close $ofh;
my $rc = sysami::util::run_editor("$ENV{'TMPDIR'}/$ARGV[0].data");
unless ($rc) {
	unlink "$ENV{'TMPDIR'}/$ARGV[0].data";
	die "error!!! did you want that?" unless $rc;
}
print "done editing, importing zone to database \n";
my $dbh = vdb_open();
die "no db\n" unless defined $dbh;
my $user = get_user(dbh=>$dbh,username=>$ENV{'DNS_ADMIN'});
die "no user" unless defined $user;
z_import($ARGV[0],$user,"$ENV{'TMPDIR'}/$ARGV[0].data",$dbh);
unlink "$ENV{'TMPDIR'}/$ARGV[0].data";
exit(0);

